require: rubocop-rspec
AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - bin/**/*
    - db/**/*
    - vendor/**/*
    - Guardfile
Rails:
  Enabled: true
Metrics/LineLength:
  Max: 100
Style/Documentation:
  Enabled: false