scss_files: 'app/assets/stylesheets/**/*.scss'

linters:
  FinalNewline:
    enabled: true
    present: false

  SelectorFormat:
    enabled: true
    convention: snake_case # or 'strict_BEM', or 'hyphenated_BEM', or 'snake_case', or 'camel_case', or a regex pattern
